artifacts_config:
  artifacts_dir: artifacts


  data_ingestion_config:
    dataset_download_url: https://github.com/Xaps23/Book-Buddy/raw/refs/heads/main/books_data.zip
    dataset_dir: "artifacts/dataset"
    ingested_dir: "artifacts/ingested_data"
    raw_data_dir: "artifacts/raw_data"

  
  data_validation_config:

    clean_data_dir: "artifacts/clean_data"
    serialized_object_dir: "artifacts/serialized_object"
    books_csv_file: "BX-Books.csv"
    ratings_csv_file: "BX-Book-Ratings.csv"

  data_transformation_config:
    transformed_data_dir: "artifacts/transformed_data"
    
 
