artifacts_config:
  artifacts_dir: artifacts


  data_ingestion_config:
    dataset_download_url: https://github.com/Xaps23/Book-Buddy/raw/refs/heads/main/books_data.zip
    dataset_dir: "artifacts/dataset"
    ingested_dir: "artifacts/ingested_data"
    raw_data_dir: "artifacts/raw_data"

  